name: leuke
description: Leuke - A social platform for Videos.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.3.0+15
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.3
  mvc_pattern: 8.1.1
  global_configuration: ^2.0.0-nullsafety.1
  http: 0.13.3
  convex_bottom_bar: ^3.0.0
  shared_preferences: ^2.0.5
  cached_network_image: 3.1.0+1
  assets_audio_player: 3.0.3+6
  like_button: ^2.0.3
  awesome_dialog: ^2.1.1
  camera: ^0.9.4+4
  image_picker: 0.8.4+4
  visibility_detector: 0.1.5
  dio: 4.0.0
  photo_view: ^0.13.0
  flutter_facebook_auth: 3.5.6
  sign_in_with_apple: 3.2.0
  google_sign_in: ^5.2.0
  video_player: ^2.2.7
  sliding_up_panel: ^2.0.0+1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  percent_indicator: 3.4.0
  device_info: ^2.0.0
  shimmer: 2.0.0
  skeleton_loader: ^2.0.0+4
  flutter_native_timezone: 1.0.10
  change_app_package_name: ^1.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  share: ^2.0.4
  grouped_list: ^4.1.0
  fluttertoast: ^8.0.8
  flutter_xlider: 3.4.0
  flutter_circular_slider: 2.5.0
  url_launcher: ^6.0.3
  flutter_cache_manager: ^3.0.1
  pin_code_fields: 7.0.0
  dotted_border: ^2.0.0
  dropdown_search: ^2.0.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_svg: 0.23.0+1
  velocity_x: ^3.0.0
  flutter_phoenix: ^1.0.0
  liquid_progress_indicator_ns: 1.0.0
  google_mobile_ads: ^0.12.1+1
  uni_links: ^0.5.1
  permission_handler: ^8.1.2
  flutter_local_notifications: 5.0.0+4
  platform_device_id: 1.0.1
  firebase_messaging: 11.1.0
  pusher_client:
    path: ./packages_list/pusher_client
  laravel_chat:
    path: ./packages_list/laravel_chat
  video_trimmer:
    path: ./packages_list/video_trimmer
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  emoji_picker_flutter: 1.0.7
  animated_text_kit: 4.2.1
  flutter_swiper_plus: ^2.0.4
  wakelock: ^0.5.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/images/
    - assets/icons/
    - assets/pics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ProductSans
    fonts:
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 200
      - asset: assets/fonts/ProductSans-Light.ttf
        weight: 300
      - asset: assets/fonts/ProductSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/ProductSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 700
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 800
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
