name: laravel_chat
description: Port of official Laravel Echo package for your Flutter apps.
version: 1.0.0-beta.1
homepage: https://github.com/kakajansh/echo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
